(() => {
  const letters = i => String.fromCharCode(65 + i);
  const conceptReason = (option, clue) => {
    const s = String(option);
    const rules = [
      [/K-nearest|k-NN/i, "k-NN is a supervised algorithm that predicts from the labels of nearby examples."],
      [/K-means/i, "K-means is unsupervised clustering used to group similar unlabeled examples."],
      [/ARIMA/i, "ARIMA is a time-series forecasting method, not a general classifier."],
      [/linear regression/i, "Linear regression predicts a continuous numeric value rather than a class label."],
      [/SageMaker Clarify/i, "SageMaker Clarify is for bias detection and model explainability."],
      [/Model Monitor/i, "SageMaker Model Monitor watches deployed models for data/model quality drift over time."],
      [/Model Cards/i, "SageMaker Model Cards standardize documentation of a model's purpose, risk, performance, and limitations."],
      [/Data Wrangler/i, "SageMaker Data Wrangler is primarily for preparing, cleaning, and transforming data."],
      [/Feature Store/i, "SageMaker Feature Store centrally stores and shares reusable ML features."],
      [/Ground Truth/i, "SageMaker Ground Truth is for labeling training data."],
      [/Personalize/i, "Amazon Personalize builds personalized recommendation experiences."],
      [/Rekognition/i, "Amazon Rekognition analyzes images and video."],
      [/Comprehend/i, "Amazon Comprehend provides managed NLP capabilities such as sentiment, entities, and toxicity detection."],
      [/Transcribe/i, "Amazon Transcribe converts speech or audio to text."],
      [/Translate/i, "Amazon Translate translates text between languages."],
      [/Textract/i, "Amazon Textract extracts text and structured data from documents."],
      [/Polly/i, "Amazon Polly converts text to speech."],
      [/Bedrock/i, "Amazon Bedrock provides managed access to foundation models and generative AI capabilities."],
      [/KMS/i, "AWS KMS creates and manages encryption keys."],
      [/Macie/i, "Amazon Macie discovers and helps protect sensitive data in Amazon S3."],
      [/CloudTrail/i, "AWS CloudTrail records AWS API activity for auditing."],
      [/CloudWatch/i, "Amazon CloudWatch provides operational monitoring, logs, and metrics."],
      [/PrivateLink/i, "AWS PrivateLink provides private connectivity to supported AWS services without traversing the public internet."],
      [/Config/i, "AWS Config records resource configuration and can evaluate configuration compliance."],
      [/Audit Manager/i, "AWS Audit Manager automates evidence collection and helps assess controls against compliance frameworks."],
      [/fine-tun/i, "Fine-tuning changes model weights using task-specific examples to alter model behavior for a specialized use case."],
      [/RAG|Retrieval Augmented/i, "RAG retrieves external knowledge at inference time without retraining model weights."],
      [/prompt engineering/i, "Prompt engineering changes instructions and context without changing model weights."],
      [/temperature/i, "Temperature controls output randomness; lowering it generally makes responses more deterministic."],
      [/few-shot/i, "Few-shot prompting includes a small number of examples in the prompt."],
      [/zero-shot/i, "Zero-shot prompting gives an instruction without examples."],
      [/chain-of-thought/i, "Chain-of-thought prompting asks the model to work through intermediate reasoning steps."],
      [/supervised/i, "Supervised learning trains from labeled examples."],
      [/unsupervised/i, "Unsupervised learning finds structure in unlabeled data."],
      [/reinforcement/i, "Reinforcement learning learns actions from rewards and penalties."],
      [/classification/i, "Classification predicts a discrete category or label."],
      [/regression/i, "Regression predicts a continuous numeric value."],
      [/clustering/i, "Clustering groups similar examples, typically without labels."],
      [/BERTScore/i, "BERTScore evaluates semantic similarity between generated and reference text using contextual embeddings."],
      [/ROUGE/i, "ROUGE measures overlap with reference text and is commonly associated with summarization evaluation."],
      [/F1/i, "F1 is the harmonic mean of precision and recall."],
      [/AUC/i, "AUC evaluates a classifier's ability to separate classes across thresholds."],
      [/small language model|SLM/i, "A smaller model is more suitable when device constraints and low-latency local inference matter."],
      [/large language model|LLM/i, "A large model typically needs more compute and is less suitable when the requirement prioritizes edge latency."],
      [/computer vision/i, "Computer vision interprets visual information such as images and video."],
      [/image processing/i, "Image processing transforms images; it is not the broader AI task of understanding image content."],
      [/logistic regression/i, "Logistic regression is an interpretable supervised model whose coefficients can be inspected and adjusted."],
      [/neural network|deep learning/i, "Neural networks can model complex relationships but their learned parameters are not as directly interpretable as simple linear models."],
      [/code|rules|simple rules/i, "A deterministic calculation should use ordinary code when ML adds no value."],
    ];
    const hit = rules.find(([re]) => re.test(s));
    return hit ? hit[1] : `${s} does not best satisfy the decisive requirement: ${clue}.`;
  };

  function q(q, opts, ans, why, clue, tip, meta={}) {
    const correct = ans.map(i => `${letters(i)}. ${opts[i]}`).join(" / ");
    const incorrectReasons = {};
    opts.forEach((o,i) => { if (!ans.includes(i)) incorrectReasons[i] = conceptReason(o, clue); });
    return {
      q, opts, ans,
      selectCount: ans.length > 1 ? ans.length : 1,
      why,
      explanation: {
        correctAnswer: correct,
        correctReason: why + ` The decisive clue is **${clue}**.`,
        incorrectReasons,
        examClue: clue,
        examTip: tip,
        transferCheck: meta.transferCheck || "",
        rememberThis: meta.rememberThis || "",
        takeaway: { signal: clue, think: tip, contrast: meta.contrast || "" }
      },
      status: "imported mock question",
      task: meta.task || "Mock Exam",
      taskName: meta.taskName || "AIF-C01 mixed-domain practice",
      difficulty: meta.difficulty || "exam-style",
      source: "ExamPrepper"
    };
  }

  function match(qtext, rows, choices, ans, why, clue, tip, meta={}) {
    return {
      type: "matching",
      q: qtext,
      rows,
      choices,
      ans,
      why,
      explanation: {
        correctAnswer: rows.map((r,i)=>`${r} → ${choices[ans[i]]}`).join(" | "),
        correctReason: why + ` The decisive clue is **${clue}**.`,
        incorrectReasons: {},
        examClue: clue,
        examTip: tip,
        transferCheck: meta.transferCheck || "",
        rememberThis: meta.rememberThis || "",
        takeaway: { signal: clue, think: tip, contrast: meta.contrast || "" }
      },
      status: "imported hotspot/matching question",
      task: meta.task || "Mock Exam",
      taskName: meta.taskName || "AIF-C01 mixed-domain practice",
      difficulty: meta.difficulty || "exam-style",
      source: "ExamPrepper"
    };
  }

  const questions = [
    q("A company makes forecasts each quarter to decide how to optimize operations to meet expected demand. The company uses ML models to make these forecasts. An AI practitioner is writing a report about the trained ML models to provide transparency and explainability to company stakeholders. What should the AI practitioner include in the report to meet the transparency and explainability requirements?",
      ["Code for model training","Partial dependence plots (PDPs)","Sample data for training","Model convergence tables"],[1],
      "Partial dependence plots show how changes in one or more features influence model predictions, helping stakeholders understand model behavior.",
      "transparency and explainability of model predictions",
      "When a question asks how a feature affects predictions, think explainability visualizations such as PDPs."),

    q("A company wants to use language models to create an application for inference on edge devices. The inference must have the lowest latency possible. Which solution will meet these requirements?",
      ["Deploy optimized small language models (SLMs) on edge devices.","Deploy optimized large language models (LLMs) on edge devices.","Incorporate a centralized small language model (SLM) API for asynchronous communication with edge devices.","Incorporate a centralized large language model (LLM) API for asynchronous communication with edge devices."],[0],
      "Running an optimized small language model directly on the edge avoids network round trips and uses less compute than an LLM.",
      "edge devices + lowest latency",
      "For lowest edge latency, prefer an optimized smaller model running locally rather than a centralized API."),

    q("A company is developing a mobile ML app that uses a phone's camera to diagnose and treat insect bites. The company wants to train an image classification model by using a diverse dataset of insect bite photos from different genders, ethnicities, and geographic locations around the world. Which principle of responsible AI does the company demonstrate in this scenario?",
      ["Fairness","Explainability","Governance","Transparency"],[0],
      "Using representative data across demographic and geographic groups helps reduce systematic performance differences between groups.",
      "diverse dataset across demographic groups",
      "Diverse, representative training data is a fairness clue."),

    q("A company is developing an ML model to make loan approvals. The company must implement a solution to detect bias in the model. The company must also be able to explain the model's predictions. Which solution will meet these requirements?",
      ["Amazon SageMaker Clarify","Amazon SageMaker Data Wrangler","Amazon SageMaker Model Cards","AWS AI Service Cards"],[0],
      "SageMaker Clarify supports bias analysis and model explainability, including feature attribution.",
      "detect bias + explain predictions",
      "Bias + explainability in SageMaker points to SageMaker Clarify."),

    q("A company has developed a generative text summarization model by using Amazon Bedrock. The company will use Amazon Bedrock automatic model evaluation capabilities. Which metric should the company use to evaluate the accuracy of the model?",
      ["Area Under the ROC Curve (AUC) score","F1 score","BERTScore","Real world knowledge (RWK) score"],[2],
      "BERTScore compares generated text with reference text using contextual embeddings, so it can capture semantic similarity even when wording differs.",
      "generative text summarization accuracy",
      "For semantic similarity of generated text to a reference, think BERTScore."),

    q("An AI practitioner wants to predict the classification of flowers based on petal length, petal width, sepal length, and sepal width. Which algorithm meets these requirements?",
      ["K-nearest neighbors (k-NN)","K-mean","Autoregressive Integrated Moving Average (ARIMA)","Linear regression"],[0],
      "The target is a flower class, and k-NN can perform supervised classification from labeled examples using nearby feature vectors.",
      "predict a category from measured features",
      "Category prediction is classification. k-NN is the classification algorithm among these choices."),

    q("A company is using custom models in Amazon Bedrock for a generative AI application. The company wants to use a company managed encryption key to encrypt the model artifacts that the model customization jobs create. Which AWS service meets these requirements?",
      ["AWS Key Management Service (AWS KMS)","Amazon Inspector","Amazon Macie","AWS Secrets Manager"],[0],
      "AWS KMS is the AWS service for creating and controlling customer managed encryption keys used to protect data and model artifacts.",
      "company managed encryption key",
      "Encryption keys → AWS KMS."),

    q("A company wants to use large language models (LLMs) to produce code from natural language code comments. Which LLM feature meets these requirements?",
      ["Text summarization","Text generation","Text completion","Text classification"],[2],
      "Natural-language comments can act as the beginning/context of a sequence that the LLM completes with code, making text completion the best fit among the choices.",
      "produce code that continues from a natural-language comment",
      "When the prompt is a prefix/comment and the model should continue it with code, think completion."),

    q("A company is introducing a mobile app that helps users learn foreign languages. The app makes text more coherent by calling a large language model (LLM). The company collected a diverse dataset of text and supplemented the dataset with examples of more readable versions. The company wants the LLM output to resemble the provided examples. Which metric should the company use to assess whether the LLM meets these requirements?",
      ["Value of the loss function","Semantic robustness","Recall-Oriented Understudy for Gisting Evaluation (ROUGE) score","Latency of the text generation"],[2],
      "ROUGE compares generated text with reference examples using overlap-based measures and is commonly used when generated wording should resemble reference text.",
      "output should resemble provided reference examples",
      "Reference-text overlap, especially for summarization-like outputs, points to ROUGE."),

    q("A company notices that its foundation model (FM) generates images that are unrelated to the prompts. The company wants to modify the prompt techniques to decrease unrelated images. Which solution meets these requirements?",
      ["Use zero-shot prompts.","Use negative prompts.","Use positive prompts.","Use ambiguous prompts."],[1],
      "Negative prompting explicitly tells an image-generation model what should not appear, helping suppress unwanted or unrelated visual elements.",
      "decrease unwanted image content through prompting",
      "Image generation + exclude unwanted elements → negative prompt."),

    q("A company wants to use a large language model (LLM) to generate concise, feature-specific descriptions for the company’s products. Which prompt engineering technique meets these requirements?",
      ["Create one prompt that covers all products. Edit the responses to make the responses more specific, concise, and tailored to each product.","Create prompts for each product category that highlight the key features. Include the desired output format and length for each prompt response.","Include a diverse range of product features in each prompt to generate creative and unique descriptions.","Provide detailed, product-specific prompts to ensure precise and customized descriptions."],[1],
      "Category-specific prompts that state the relevant features plus desired format and length directly constrain the response to be concise and feature-focused while remaining reusable.",
      "concise + feature-specific + desired format/length",
      "Strong prompts explicitly state the task, relevant context, and output constraints."),

    q("A company is developing an ML model to predict customer churn. The model performs well on the training dataset but does not accurately predict churn for new data. Which solution will resolve this issue?",
      ["Decrease the regularization parameter to increase model complexity.","Increase the regularization parameter to decrease model complexity.","Add more features to the input data.","Train the model for more epochs."],[1],
      "Good training performance but poor performance on new data indicates overfitting. Increasing regularization reduces effective model complexity and can improve generalization.",
      "good on training data, poor on new data",
      "Great train performance + poor test/new-data performance → overfitting → add regularization or simplify."),

    q("A company wants to build an ML model by using Amazon SageMaker. The company needs to share and manage variables for model development across multiple teams. Which SageMaker feature meets these requirements?",
      ["Amazon SageMaker Feature Store","Amazon SageMaker Data Wrangler","Amazon SageMaker Clarify","Amazon SageMaker Model Cards"],[0],
      "SageMaker Feature Store is a centralized repository for storing, sharing, and reusing ML features across teams and models.",
      "share and manage ML features/variables across teams",
      "Reusable shared features → SageMaker Feature Store."),

    q("A company is implementing intelligent agents to provide conversational search experiences for its customers. The company needs a database service that will support storage and queries of embeddings from a generative AI model as vectors in the database. Which AWS service will meet these requirements?",
      ["Amazon Athena","Amazon Aurora PostgreSQL","Amazon Redshift","Amazon EMR"],[1],
      "Aurora PostgreSQL can use the pgvector extension to store vector embeddings and perform similarity search.",
      "store and query embeddings as vectors",
      "Vector storage in a relational AWS database → PostgreSQL with pgvector, including Aurora PostgreSQL."),

    q("A financial institution is building an AI solution to make loan approval decisions by using a foundation model (FM). For security and audit purposes, the company needs the AI solution's decisions to be explainable. Which factor relates to the explainability of the AI solution's decisions?",
      ["Model complexity","Training time","Number of hyperparameters","Deployment time"],[0],
      "Model complexity directly affects interpretability: more complex models are generally harder to explain than simpler models.",
      "explainability of decisions",
      "Explainability questions often hinge on the trade-off between model complexity and interpretability."),

    q("A pharmaceutical company wants to analyze user reviews of new medications and provide a concise overview for each medication. Which solution meets these requirements?",
      ["Create a time-series forecasting model to analyze the medication reviews by using Amazon Personalize.","Create medication review summaries by using Amazon Bedrock large language models (LLMs).","Create a classification model that categorizes medications into different groups by using Amazon SageMaker.","Create medication review summaries by using Amazon Rekognition."],[1],
      "Summarizing free-form review text is a generative language task, which is well suited to LLMs available through Amazon Bedrock.",
      "summarize text reviews",
      "Generate or summarize natural-language content → foundation model/LLM on Amazon Bedrock."),

    q("A company wants to build a lead prioritization application for its employees to contact potential customers. The application must give employees the ability to view and adjust the weights assigned to different variables in the model based on domain knowledge and expertise. Which ML model type meets these requirements?",
      ["Logistic regression model","Deep learning model built on principal components","K-nearest neighbors (k-NN) model","Neural network"],[0],
      "Logistic regression exposes explicit feature coefficients that can be inspected and adjusted, making it more interpretable than the other options.",
      "view and adjust feature weights",
      "Need interpretable, directly inspectable feature weights → linear/logistic regression."),

    match("A company wants to build an ML application. Select and order the correct steps from the following list to develop a well-architected ML workload. Each step should be selected one time.",
      ["Step 1","Step 2","Step 3","Step 4"],
      ["Deploy model","Develop model","Monitor model","Define business goal and frame ML problem"],
      [3,1,0,2],
      "A well-architected ML workload starts by defining the business goal, then developing the model, deploying it, and monitoring it after deployment.",
      "ML lifecycle order",
      "Frame the business problem first; monitoring comes after deployment."),

    q("Which strategy will determine if a foundation model (FM) effectively meets business objectives?",
      ["Evaluate the model's performance on benchmark datasets.","Analyze the model's architecture and hyperparameters.","Assess the model's alignment with specific use cases.","Measure the computational resources required for model deployment."],[2],
      "Business effectiveness is determined by how well the model supports the actual target use cases and business outcomes, not only technical benchmarks.",
      "meets business objectives",
      "Business objective questions → evaluate against the intended use case and business KPI."),

    q("A company needs to train an ML model to classify images of different types of animals. The company has a large dataset of labeled images and will not label more data. Which type of learning should the company use to train the model?",
      ["Supervised learning","Unsupervised learning","Reinforcement learning","Active learning"],[0],
      "The dataset already contains labels and the goal is image classification, so supervised learning is appropriate.",
      "labeled images + classification",
      "Labeled data → supervised learning."),

    q("Which phase of the ML lifecycle determines compliance and regulatory requirements?",
      ["Feature engineering","Model training","Data collection","Business goal identification"],[3],
      "Compliance, risk, and regulatory constraints should be identified while framing the business problem so they can shape the entire ML solution.",
      "determine requirements before building",
      "Business and compliance requirements are established during problem framing, before data preparation and training."),

    q("A food service company wants to develop an ML model to help decrease daily food waste and increase sales revenue. The company needs to continuously improve the model's accuracy. Which solution meets these requirements?",
      ["Use Amazon SageMaker and iterate with newer data.","Use Amazon Personalize and iterate with historical data.","Use Amazon CloudWatch to analyze customer orders.","Use Amazon Rekognition to optimize the model."],[0],
      "SageMaker supports the end-to-end ML lifecycle, including retraining and iterating with newer data to improve model accuracy.",
      "continuously improve a custom ML model with newer data",
      "Build/retrain/iterate a custom ML model → SageMaker."),

    q("A company has developed an ML model to predict real estate sale prices. The company wants to deploy the model to make predictions without managing servers or infrastructure. Which solution meets these requirements?",
      ["Deploy the model on an Amazon EC2 instance.","Deploy the model on an Amazon Elastic Kubernetes Service (Amazon EKS) cluster.","Deploy the model by using Amazon CloudFront with an Amazon S3 integration.","Deploy the model by using an Amazon SageMaker endpoint."],[3],
      "A SageMaker endpoint is a managed inference deployment option that removes the need to directly manage servers for model serving.",
      "managed model inference deployment",
      "Deploy a trained model for managed inference → SageMaker endpoint."),

    q("A company wants to use generative AI to increase developer productivity and software development. The company wants to use Amazon Q Developer. What can Amazon Q Developer do to help the company meet these requirements?",
      ["Create software snippets, reference tracking, and open source license tracking.","Run an application without provisioning or managing servers.","Enable voice commands for coding and providing natural language search.","Convert audio files to text documents by using ML models."],[0],
      "Amazon Q Developer can generate code suggestions/snippets and includes reference tracking to help developers understand code similarity and licensing context.",
      "developer productivity with Amazon Q Developer",
      "Coding assistant, code suggestions, transformations, security scanning, and reference tracking → Amazon Q Developer."),

    q("A company wants to develop an AI application to help its employees check open customer claims, identify details for a specific claim, and access documents for a claim. Which solution meets these requirements?",
      ["Use Agents for Amazon Bedrock with Amazon Fraud Detector to build the application.","Use Agents for Amazon Bedrock with Amazon Bedrock knowledge bases to build the application.","Use Amazon Personalize with Amazon Bedrock knowledge bases to build the application.","Use Amazon SageMaker to build the application by training a new ML model."],[1],
      "Bedrock Agents can orchestrate actions, while Knowledge Bases provide retrieval over claim documents and enterprise data for grounded answers.",
      "take actions + retrieve claim documents",
      "Agents = actions/orchestration; Knowledge Bases = RAG over your documents."),

    q("A manufacturing company uses AI to inspect products and find any damages or defects. Which type of AI application is the company using?",
      ["Recommendation system","Natural language processing (NLP)","Computer vision","Image processing"],[2],
      "Detecting visible product defects from images or video is a computer vision task.",
      "inspect visual defects",
      "Images/video understanding and defect detection → computer vision."),

    q("A company wants to create an ML model to predict customer satisfaction. The company needs fully automated model tuning. Which AWS service meets these requirements?",
      ["Amazon Personalize","Amazon SageMaker","Amazon Athena","Amazon Comprehend"],[1],
      "Amazon SageMaker provides automatic model tuning and broader model development capabilities for custom ML workloads.",
      "fully automated model tuning",
      "Hyperparameter/model tuning for custom ML → SageMaker."),

    q("Which technique can a company use to lower bias and toxicity in generative AI applications during the post-processing ML lifecycle?",
      ["Human-in-the-loop","Data augmentation","Feature engineering","Adversarial training"],[0],
      "Human review can be applied after model output generation to detect and correct biased, toxic, or otherwise unsafe outputs.",
      "post-processing generated outputs",
      "Post-processing safety check → human-in-the-loop review."),

    q("A bank has fine-tuned a large language model (LLM) to expedite the loan approval process. During an external audit of the model, the company discovered that the model was approving loans at a faster pace for a specific demographic than for other demographics. How should the bank fix this issue MOST cost-effectively?",
      ["Include more diverse training data. Fine-tune the model again by using the new data.","Use Retrieval Augmented Generation (RAG) with the fine-tuned model.","Use AWS Trusted Advisor checks to eliminate bias.","Pre-train a new LLM with more diverse training data."],[0],
      "The issue is demographic bias in model behavior. Adding more representative training examples and re-fine-tuning directly addresses the bias at far lower cost than pre-training a new LLM.",
      "bias from insufficiently representative training data",
      "Bias in a fine-tuned model → improve training data diversity and retrain/fine-tune; RAG does not fix learned bias."),

    match("A company has developed a large language model (LLM) and wants to make the LLM available to multiple internal teams. The company needs to select the appropriate inference mode for each team.",
      ["The company's chatbot needs predictions from the LLM to understand users' intent with minimal latency.","A data processing job needs to query the LLM to process gigabytes of text files on weekends.","The company's engineering team needs to create an API that can process small pieces of text content and provide low-latency predictions."],
      ["Batch transform","Real-time inference"],
      [1,0,1],
      "Interactive and API use cases that need low latency require real-time inference; large scheduled weekend processing is a batch workload.",
      "low latency vs scheduled bulk processing",
      "Immediate response → real-time; large offline bulk workload → batch."),

    q("A company needs to log all requests made to its Amazon Bedrock API. The company must retain the logs securely for 5 years at the lowest possible cost. Which combination of AWS service and storage class meets these requirements? (Choose two.)",
      ["AWS CloudTrail","Amazon CloudWatch","AWS Audit Manager","Amazon S3 Intelligent-Tiering","Amazon S3 Standard"],[0,3],
      "CloudTrail records API activity, and S3 Intelligent-Tiering is the lower-overhead long-term storage choice among the listed S3 classes for data whose access pattern may change.",
      "API audit logging + long-term cost optimization",
      "Who called an AWS API → CloudTrail. Long retention with changing access → S3 Intelligent-Tiering.",
      {contrast:"CloudWatch monitors operational telemetry; Audit Manager collects audit evidence but is not the API activity log."}),

    q("An ecommerce company wants to improve search engine recommendations by customizing the results for each user of the company’s ecommerce platform. Which AWS service meets these requirements?",
      ["Amazon Personalize","Amazon Kendra","Amazon Rekognition","Amazon Transcribe"],[0],
      "Amazon Personalize is designed to create personalized recommendations and ranking experiences from user behavior.",
      "customize recommendations per user",
      "Personalized recommendations → Amazon Personalize."),

    q("A hospital is developing an AI system to assist doctors in diagnosing diseases based on patient records and medical images. To comply with regulations, the sensitive patient data must not leave the country the data is located in. Which data governance strategy will ensure compliance and protect patient privacy?",
      ["Data residency","Data quality","Data discoverability","Data enrichment"],[0],
      "Data residency controls where data is stored and processed so it remains within required geographic or jurisdictional boundaries.",
      "data must not leave the country",
      "Geographic location requirement → data residency/sovereignty."),

    q("A company needs to monitor the performance of its ML systems by using a highly scalable AWS service. Which AWS service meets these requirements?",
      ["Amazon CloudWatch","AWS CloudTrail","AWS Trusted Advisor","AWS Config"],[0],
      "Amazon CloudWatch provides scalable monitoring through metrics, logs, alarms, and dashboards.",
      "monitor system performance",
      "Operational metrics/performance monitoring → CloudWatch."),

    q("A financial institution is using Amazon Bedrock to develop an AI application. The application is hosted in a VPC. To meet regulatory compliance standards, the VPC is not allowed access to any internet traffic. Which AWS service or feature will meet these requirements?",
      ["AWS PrivateLink","Amazon Macie","Amazon CloudFront","Internet gateway"],[0],
      "AWS PrivateLink provides private VPC connectivity to supported AWS services without requiring public internet access.",
      "private service access with no internet",
      "Keep traffic private inside AWS → VPC endpoint/AWS PrivateLink."),

    q("An AI practitioner is developing a prompt for an Amazon Titan model. The model is hosted on Amazon Bedrock. The AI practitioner is using the model to solve numerical reasoning challenges. The AI practitioner adds the following phrase to the end of the prompt: “Ask the model to show its work by explaining its reasoning step by step.” Which prompt engineering technique is the AI practitioner using?",
      ["Chain-of-thought prompting","Prompt injection","Few-shot prompting","Prompt templating"],[0],
      "Requesting explicit step-by-step reasoning is the defining pattern of chain-of-thought prompting.",
      "think/explain step by step",
      "Step-by-step reasoning request → chain-of-thought prompting."),

    q("Which AWS service makes foundation models (FMs) available to help users build and scale generative AI applications?",
      ["Amazon Q Developer","Amazon Bedrock","Amazon Kendra","Amazon Comprehend"],[1],
      "Amazon Bedrock provides managed access to foundation models from AWS and third-party providers for generative AI applications.",
      "managed access to foundation models",
      "Foundation models via managed API → Amazon Bedrock."),

    q("A company is building a mobile app for users who have a visual impairment. The app must be able to hear what users say and provide voice responses. Which solution will meet these requirements?",
      ["Use a deep learning neural network to perform speech recognition.","Build ML models to search for patterns in numeric data.","Use generative AI summarization to generate human-like text.","Build custom models for image classification and recognition."],[0],
      "Among the choices, speech recognition is the capability required to interpret spoken input; a complete voice assistant would pair speech-to-text with text-to-speech for responses.",
      "spoken input and voice interaction",
      "Speech input → speech recognition/Transcribe; spoken output would use text-to-speech such as Polly."),

    q("A company wants to enhance response quality for a large language model (LLM) for complex problem-solving tasks. The tasks require detailed reasoning and a step-by-step explanation process. Which prompt engineering technique meets these requirements?",
      ["Few-shot prompting","Zero-shot prompting","Directional stimulus prompting","Chain-of-thought prompting"],[3],
      "Chain-of-thought prompting is designed to encourage intermediate reasoning steps for multi-step problems.",
      "detailed reasoning + step-by-step",
      "Complex reasoning with steps → chain-of-thought."),

    q("A company wants to keep its foundation model (FM) relevant by using the most recent data. The company wants to implement a model training strategy that includes regular updates to the FM. Which solution meets these requirements?",
      ["Batch learning","Continuous pre-training","Static training","Latent training"],[1],
      "Continuous pre-training keeps adapting a foundation model with newer data so its learned knowledge remains more current.",
      "regularly update the FM with new data",
      "Ongoing domain/model knowledge updates → continuous pre-training."),

    match("A company wants to develop ML applications to improve business operations and efficiency. Select the correct ML paradigm from the following list for each use case. Each ML paradigm should be selected one or more times.",
      ["Binary classification","Multi-class classification","K-means clustering","Dimensionality reduction"],
      ["Supervised learning","Unsupervised learning"],
      [0,0,1,1],
      "Classification learns from labeled examples, while K-means clustering and dimensionality reduction are unsupervised techniques that discover structure in unlabeled data.",
      "classification vs clustering/dimensionality reduction",
      "Classification → supervised; clustering and dimensionality reduction → unsupervised."),

    q("Which option is a characteristic of AI governance frameworks for building trust and deploying human-centered AI technologies?",
      ["Expanding initiatives across business units to create long-term business value","Ensuring alignment with business standards, revenue goals, and stakeholder expectations","Overcoming challenges to drive business transformation and growth","Developing policies and guidelines for data, transparency, responsible AI, and compliance"],[3],
      "AI governance establishes policies, responsibilities, and controls around data, transparency, responsible AI, risk, and compliance.",
      "governance framework",
      "Governance → policies, controls, accountability, transparency, and compliance."),

    q("An ecommerce company is using a generative AI chatbot to respond to customer inquiries. The company wants to measure the financial effect of the chatbot on the company’s operations. Which metric should the company use?",
      ["Number of customer inquiries handled","Cost of training AI models","Cost for each customer conversation","Average handled time (AHT)"],[2],
      "Cost per customer conversation directly measures the operating cost associated with each chatbot interaction and therefore captures financial impact.",
      "financial effect on operations",
      "When asked for business/financial impact, choose a cost or revenue KPI rather than a model-quality metric."),

    q("A company wants to find groups for its customers based on the customers’ demographics and buying patterns. Which algorithm should the company use to meet this requirement?",
      ["K-nearest neighbors (k-NN)","K-means","Decision tree","Support vector machine"],[1],
      "K-means is an unsupervised clustering algorithm used to group similar customers when no predefined class label is required.",
      "find groups of similar customers",
      "Grouping/segmentation without labels → clustering → K-means."),

    q("A company’s large language model (LLM) is experiencing hallucinations. How can the company decrease hallucinations?",
      ["Set up Agents for Amazon Bedrock to supervise the model training.","Use data pre-processing and remove any data that causes hallucinations.","Decrease the temperature inference parameter for the model.","Use a foundation model (FM) that is trained to not hallucinate."],[2],
      "Lower temperature reduces randomness and makes the model choose more probable tokens, which can reduce unsupported or erratic outputs.",
      "reduce hallucinations via an inference setting",
      "Among inference parameters, lower temperature is the direct clue for more deterministic output."),

    q("A company wants to develop an educational game where users answer questions such as the following: “A jar contains six red, four green, and three yellow marbles. What is the probability of choosing a green marble from the jar?” Which solution meets these requirements with the LEAST operational overhead?",
      ["Use supervised learning to create a regression model that will predict probability.","Use reinforcement learning to train a model to return the probability.","Use code that will calculate probability by using simple rules and computations.","Use unsupervised learning to create a model that will estimate probability density."],[2],
      "This is a deterministic arithmetic problem, so simple code is cheaper, more reliable, and easier to operate than an ML model.",
      "simple deterministic calculation",
      "If explicit rules/math solve the problem, ML is unnecessary."),

    q("A company is using a large language model (LLM) on Amazon Bedrock to build a chatbot. The chatbot processes customer support requests. To resolve a request, the customer and the chatbot must interact a few times. Which solution gives the LLM the ability to use content from previous customer messages?",
      ["Turn on model invocation logging to collect messages.","Add messages to the model prompt.","Use Amazon Personalize to save conversation history.","Use Provisioned Throughput for the LLM."],[1],
      "LLMs use the context supplied with the current invocation. Including prior turns/messages in the prompt gives the model conversational context.",
      "use previous conversation turns",
      "Conversation memory for an LLM comes from passing relevant message history in context."),

    q("A company’s employees provide product descriptions and recommendations to customers when customers call the customer service center. These recommendations are based on where the customers are located. The company wants to use foundation models (FMs) to automate this process. Which AWS service meets these requirements?",
      ["Amazon Macie","Amazon Transcribe","Amazon Bedrock","Amazon Textract"],[2],
      "Amazon Bedrock provides foundation models that can generate product descriptions and contextual recommendations.",
      "use foundation models to generate responses",
      "Foundation-model application → Amazon Bedrock."),

    q("A company wants to upload customer service email messages to Amazon S3 to develop a business analysis application. The messages sometimes contain sensitive data. The company wants to receive an alert every time sensitive information is found. Which solution fully automates the sensitive information detection process with the LEAST development effort?",
      ["Configure Amazon Macie to detect sensitive information in the documents that are uploaded to Amazon S3.","Use Amazon SageMaker endpoints to deploy a large language model (LLM) to redact sensitive data.","Develop multiple regex patterns to detect sensitive data. Expose the regex patterns on an Amazon SageMaker notebook.","Ask the customers to avoid sharing sensitive information in their email messages."],[0],
      "Amazon Macie is purpose-built to discover and classify sensitive data in S3 and can generate findings with minimal custom development.",
      "automated sensitive-data discovery in S3",
      "Sensitive data in S3 → Amazon Macie."),

    match("A company is training its employees on how to structure prompts for foundation models. Select the correct prompt engineering technique from the following list for each prompt template. Each prompt engineering technique should be selected one time.",
      ["“Classify the following text as either sports, politics, or entertainment: [input text].”","“A [image 1], [image 2], and [image 3] are examples of [target class]. Classify the following image as [target class].”","“[Question.] [Instructions to follow.] Think step by step and walk me through your thinking.”"],
      ["Chain-of-thought reasoning","Few-shot learning","Zero-shot learning"],
      [2,1,0],
      "The first prompt supplies no examples, the second supplies several examples, and the third explicitly asks for step-by-step reasoning.",
      "no examples vs examples vs step-by-step reasoning",
      "No examples → zero-shot; examples → few-shot; 'step by step' → chain-of-thought."),

    match("A company is using a generative AI model to develop a digital assistant. The model’s responses occasionally include undesirable and potentially harmful content. Select the correct Amazon Bedrock filter policy from the following list for each mitigation action. Each filter policy should be selected one time.",
      ["Block input prompts or model responses that contain harmful content such as hate, insults, violence, or misconduct","Avoid subjects related to illegal investment advice or legal advice","Detect and block specific offensive terms","Detect and filter out information in the model's responses that is not grounded in the provided source information"],
      ["Content filters","Contextual grounding check","Denied topics","Word filters"],
      [0,2,3,1],
      "Bedrock Guardrails maps harmful-content categories to content filters, prohibited subject areas to denied topics, exact terms to word filters, and unsupported source-based claims to contextual grounding checks.",
      "harm category vs topic vs exact word vs grounding",
      "Content filters = harmful categories; denied topics = subjects; word filters = exact terms; grounding check = unsupported claims."),

    q("Which option is a benefit of using Amazon SageMaker Model Cards to document AI models?",
      ["Providing a visually appealing summary of a mode’s capabilities.","Standardizing information about a model’s purpose, performance, and limitations.","Reducing the overall computational requirements of a model.","Physically storing models for archival purposes."],[1],
      "SageMaker Model Cards provide a standardized way to document intended use, performance, risk, training details, and limitations for governance.",
      "standardized model documentation",
      "Model documentation for governance/audit → SageMaker Model Cards."),

    q("What does an F1 score measure in the context of foundation model (FM) performance?",
      ["Model precision and recall","Model speed in generating responses","Financial cost of operating the model","Energy efficiency of the model’s computations"],[0],
      "F1 is the harmonic mean of precision and recall, giving a single metric that balances both.",
      "F1 score",
      "F1 = balance of precision and recall."),

    q("A company deployed an AI/ML solution to help customer service agents respond to frequently asked questions. The questions can change over time. The company wants to give customer service agents the ability to ask questions and receive automatically generated answers to common customer questions. Which strategy will meet these requirements MOST cost-effectively?",
      ["Fine-tune the model regularly.","Train the model by using context data.","Pre-train and benchmark the model by using context data.","Use Retrieval Augmented Generation (RAG) with prompt engineering techniques."],[3],
      "RAG retrieves current FAQ or knowledge-base content at inference time, so changing information can be updated without repeatedly retraining the model.",
      "knowledge changes over time + cost-effective",
      "Frequently changing proprietary/current knowledge → RAG, not repeated fine-tuning."),

    q("A company built an AI-powered resume screening system. The company used a large dataset to train the model. The dataset contained resumes that were not representative of all demographics. Which core dimension of responsible AI does this scenario present?",
      ["Fairness","Explainability","Privacy and security","Transparency"],[0],
      "An unrepresentative dataset can cause systematic performance differences across demographic groups, which is a fairness concern.",
      "training data not representative of all demographics",
      "Representation imbalance across groups → fairness/bias."),

    q("A global financial company has developed an ML application to analyze stock market data and provide stock market trends. The company wants to continuously monitor the application development phases and to ensure that company policies and industry regulations are followed. Which AWS services will help the company assess compliance requirements? (Choose two.)",
      ["AWS Audit Manager","AWS Config","Amazon Inspector","Amazon CloudWatch","AWS CloudTrail"],[0,1],
      "AWS Audit Manager helps assess controls and collect compliance evidence, while AWS Config tracks resource configuration and can evaluate compliance against configuration rules.",
      "assess compliance requirements continuously",
      "Compliance assessment/evidence → Audit Manager; configuration compliance → AWS Config.",
      {contrast:"CloudTrail provides activity history and is important for auditability, but this question asks specifically for compliance assessment."}),

    q("Which metric measures the runtime efficiency of operating AI models?",
      ["Customer satisfaction score (CSAT)","Training time for each epoch","Average response time","Number of training instances"],[2],
      "Average response time measures inference latency during operation, making it a direct runtime-efficiency metric.",
      "runtime efficiency during inference",
      "Runtime efficiency → latency/response time/throughput, not training metrics."),

    q("A company wants to improve the accuracy of the responses from a generative AI application. The application uses a foundation model (FM) on Amazon Bedrock. Which solution meets these requirements MOST cost-effectively?",
      ["Fine-tune the FM.","Retrain the FM.","Train a new FM.","Use prompt engineering."],[3],
      "Prompt engineering can improve output quality without training or changing model weights, so it is typically the lowest-cost first step.",
      "improve response quality MOST cost-effectively",
      "Cheapest customization first → prompt engineering."),

    q("A company wants to identify harmful language in the comments section of social media posts by using an ML model. The company will not use labeled data to train the model. Which strategy should the company use to identify harmful language?",
      ["Use Amazon Rekognition moderation.","Use Amazon Comprehend toxicity detection.","Use Amazon SageMaker built-in algorithms to train the model.","Use Amazon Polly to monitor comments."],[1],
      "Amazon Comprehend provides managed toxicity detection for text, avoiding the need to train a custom labeled model.",
      "harmful language in text + no custom labels",
      "Toxic text detection → Amazon Comprehend toxicity detection."),

    q("A media company wants to analyze viewer behavior and demographics to recommend personalized content. The company wants to deploy a customized ML model in its production environment. The company also wants to observe if the model quality drifts over time. Which AWS service or feature meets these requirements?",
      ["Amazon Rekognition","Amazon SageMaker Clarify","Amazon Comprehend","Amazon SageMaker Model Monitor"],[3],
      "SageMaker Model Monitor is designed to monitor deployed models for data and model quality drift over time.",
      "production model quality drifts over time",
      "After deployment + drift monitoring → SageMaker Model Monitor."),

    q("A company is deploying AI/ML models by using AWS services. The company wants to offer transparency into the models’ decision-making processes and provide explanations for the model outputs. Which AWS service or feature meets these requirements?",
      ["Amazon SageMaker Model Cards","Amazon Rekognition","Amazon Comprehend","Amazon Lex"],[0],
      "Among the listed choices, SageMaker Model Cards are the governance artifact that documents model purpose, performance, risk, and intended use to improve transparency. For per-prediction feature attribution, SageMaker Clarify would be the more direct service, but it is not offered here.",
      "transparency and explanation documentation",
      "Model Cards = standardized transparency documentation; Clarify = direct bias/explainability when available as an option.",
      {contrast:"This item is somewhat imprecise because SageMaker Clarify is the AWS feature normally associated with explaining individual model predictions."}),

    q("A manufacturing company wants to create product descriptions in multiple languages. Which AWS service will automate this task?",
      ["Amazon Translate","Amazon Transcribe","Amazon Kendra","Amazon Polly"],[0],
      "Amazon Translate provides managed neural machine translation for text between supported languages.",
      "multiple languages",
      "Translate text between languages → Amazon Translate."),

    match("A company wants more customized responses to its generative AI models’ prompts. Select the correct customization methodology from the following list for each use case. Each use case should be selected one time.",
      ["The models must be taught a new domain-specific task","A limited amount of labeled data is available and more data is needed","Only unlabeled data is available"],
      ["Continued pre-training","Data augmentation","Model fine-tuning"],
      [2,1,0],
      "Fine-tuning adapts a pre-trained model to a specific labeled task, data augmentation expands limited labeled datasets, and continued pre-training uses unlabeled domain data to further adapt the model.",
      "labeled task vs scarce labeled data vs unlabeled domain data",
      "New task with labels → fine-tune; too little labeled data → augment; only unlabeled domain data → continued pre-training."),

    q("Which AWS feature records details about ML instance data for governance and reporting?",
      ["Amazon SageMaker Model Cards","Amazon SageMaker Debugger","Amazon SageMaker Model Monitor","Amazon SageMaker JumpStart"],[0],
      "SageMaker Model Cards record standardized details about models for governance, documentation, and reporting.",
      "governance and reporting documentation",
      "Governance documentation → SageMaker Model Cards."),

    q("A financial company is using ML to help with some of the company’s tasks. Which option is a use of generative AI models?",
      ["Summarizing customer complaints","Classifying customers based on product usage","Segmenting customers based on type of investments","Forecasting revenue for certain products"],[0],
      "Summarization creates new natural-language content from existing text, making it a generative AI use case. The other choices are traditional classification, clustering/segmentation, or forecasting tasks.",
      "generate a new text summary",
      "New text/image/code/audio content → generative AI; labels, groups, and numeric forecasts → traditional ML.")
  ];

  window.mockExam1 = {
    id: "mock-exam-1",
    kind: "mock",
    title: "Mock Exam 1",
    subtitle: "Full AIF-C01 Practice Exam",
    weight: "Full Mock",
    durationSeconds: 5400,
    passPercent: 72,
    questions
  };
})();