(() => {
  window.aifExamData = window.aifExamData || {};
  const guide = 'https://docs.aws.amazon.com/aws-certification/latest/ai-practitioner-01/ai-practitioner-01.html';
  const judge = 'https://docs.aws.amazon.com/bedrock/latest/userguide/model-evaluation-metrics.html';
  const letter = i => String.fromCharCode(65 + i);
  // [prompt, options, zero-based answers, rationale, clue, tip, distractor rationales,
  //  domain, provenance, official reference, optional transfer check]
  const raw = [
    // Adapted from supplied 196: deterministic classification, rather than creative generation.
    ['A Bedrock sentiment classifier gives different labels when the same review is submitted repeatedly. Which inference adjustment makes its responses more consistent?',
      ['Lower temperature','Raise temperature','Raise maximum output tokens','Increase the context window'],[0],
      'Temperature controls randomness in token selection. A lower value makes a given prompt more likely to produce the same label, although it does not guarantee perfect determinism.',
      'same review; more consistent label','Low temperature → less randomness. It does not repair an unclear classification prompt.',
      ['', 'Higher temperature increases variation.','A larger output allowance affects length, not sampling consistency.','A context window is input capacity, not the randomness setting.'],3,'Supplied 196'],
    // Supplied 197; narrowed to ingestion permissions and resource isolation.
    ['Separate teams use Bedrock knowledge bases backed by S3 customer folders. Each team must be unable to ingest another team’s objects. Which design enforces that boundary?',
      ['Give each knowledge base a distinct service role limited to that team’s S3 objects','Use one full-access service role and ask teams to enter their team name in prompts','Remove names from objects but permit all teams to read every folder','Give every knowledge base a full-access service role and restrict only console users'],[0],
      'The role Bedrock assumes for each knowledge base needs least-privilege S3 permissions scoped to its own source objects. Prompt wording and console access do not constrain what a broadly authorized service role can retrieve.',
      'teams can ingest only their own S3 objects','Enforce data boundaries in the service role and S3 policy, not in a prompt.',
      ['', 'A model prompt is not an authorization control.','Redaction does not prevent cross-team access.','A full-access ingestion role can still read other teams’ objects.'],5,'Supplied 197','https://docs.aws.amazon.com/bedrock/latest/userguide/kb-permissions.html'],
    ['A healthcare chatbot must mask patient identifiers in Bedrock responses and alert operators when its guardrail intervenes. Which pairing addresses both needs?',
      ['Amazon Macie plus an S3 event notification','CloudTrail event history alone','Bedrock Guardrails sensitive-information filter plus a CloudWatch alarm on guardrail metrics','SageMaker Model Monitor alone'],[2],
      'Bedrock Guardrails can filter or mask sensitive information in model responses. Bedrock publishes guardrail runtime metrics to CloudWatch, where an alarm can notify operators of interventions.',
      'mask identifiers in responses; alert on interventions','Guardrails control runtime content; CloudWatch watches the intervention metric.',
      ['Macie discovers sensitive data in S3 rather than filtering live model output.','CloudTrail audits API activity, not the patient text of each response.','', 'Model Monitor addresses deployed ML quality and drift, not this Bedrock output policy.'],5,'Supplied 198','https://docs.aws.amazon.com/bedrock/latest/userguide/monitoring-guardrails-cw-metrics.html'],
    ['An education app knows each learner’s age band and needs to explain the same concept at an appropriate reading level without model training. What should it do first?',
      ['Fine-tune a separate model for each age band','Include the age band and desired style in the prompt','Increase chain-of-thought output','Shorten every answer regardless of age'],[1],
      'An instruction in the prompt can set audience, vocabulary, and tone for each request with little implementation work. Fine-tuning is a larger persistent customization step that this dynamic style requirement does not justify.',
      'style changes per learner; no model training','Put a changing audience requirement in the current prompt.',
      ['Separate tuned models add training and maintenance work.','', 'Exposing reasoning does not by itself set an age-appropriate style.','Length alone does not determine clarity or reading level.'],3,'Supplied 200'],
    ['A lender wants to assess whether an LLM disadvantages protected groups. Which TWO actions address that responsible-AI goal? (Choose two.)',
      ['Measure outcome differences across groups','Raise response temperature','Review and improve underrepresented training examples','Only reduce maximum output length','Skip validation after deployment'],[0,2],
      'Group-level fairness metrics reveal unequal outcomes, while improving representation can reduce a data source of bias. Neither guarantees fairness, so the team should keep evaluating across the model lifecycle.',
      'disadvantages protected groups; two complementary actions','Measure disparities and address biased or incomplete data.',
      ['', 'Temperature changes sampling, not the fairness evaluation.','', 'Output length does not establish equitable decisions.','Without later validation, new disparities could go unnoticed.'],4,'Supplied 203'],
    ['Before training, analysts profile a new dataset, plot distributions, and inspect correlations for surprising patterns. What lifecycle stage is this?',
      ['Exploratory data analysis','Hyperparameter tuning','Model deployment','Inference'],[0],
      'Exploratory data analysis uses summaries and visualizations to understand the dataset and spot data-quality issues before selecting features or training a model.',
      'profile, distributions, correlations before training','Inspect and visualize the data → exploratory data analysis.',
      ['', 'Hyperparameter tuning compares training settings.','Deployment makes a trained model available for use.','Inference uses a trained model to make predictions.'],1,'Supplied 204'],
    ['A document-restoration tool must predict missing words using both the text before and after each blank. Which model architecture is particularly suited to this masked-word task?',
      ['Topic model','K-means clustering','BERT-style bidirectional language model','Linear regression'],[2],
      'BERT-style models learn bidirectional context through masked language modeling, so words on both sides help infer a missing token. The objective here is contextual text completion.',
      'missing word; context on both sides','Masked language modeling and bidirectional context point to BERT.',
      ['Topic modeling discovers themes across documents.','Clustering groups similar records without predicting a masked word.','', 'Linear regression estimates a numeric value.'],2,'Supplied 205'],
    ['A chatbot classifies messages into Billing, Cancellation, or Technical. To build a few-shot prompt, which examples should the team provide?',
      ['User messages paired with the correct intent','Responses paired with an arbitrary category','Categories paired only with bot replies','Unlabeled messages only'],[0],
      'Few-shot intent classification shows the model representative inputs with their correct output labels. This demonstrates the mapping it must apply to the new user message.',
      'few-shot intent classification','Examples must pair input messages with target intent labels.',
      ['', 'Bot responses are not the user input being classified.','Intent-to-reply pairs teach response generation instead.','Unlabeled examples do not demonstrate the desired answer.'],3,'Supplied 207'],
    ['A Bedrock prompt contains ten demonstrations and runs once per day. Quality remains acceptable with fewer examples. What is the simplest first cost optimization?',
      ['Purchase Provisioned Throughput','Remove unneeded demonstration tokens and re-evaluate','Increase the output-token allowance','Fine-tune immediately'],[1],
      'On-demand inference cost is influenced by input and output tokens. Shortening an oversized prompt can reduce cost without introducing the fixed commitment or training effort of other choices; verify that quality remains adequate.',
      'ten examples; once daily; reduce cost','Trim repeated prompt tokens before buying capacity or training.',
      ['Reserved capacity is unlikely to suit a once-daily call.','', 'Allowing more output can increase token use.','Fine-tuning adds work and expense and is not the first optimization here.'],3,'Supplied 208','https://aws.amazon.com/bedrock/pricing/'],
    ['A fine-tuning dataset accidentally contains confidential account numbers. The team wants to prevent a newly deployed custom model from learning those numbers. What action best addresses the root cause?',
      ['Remove the numbers from the training data and retrain a replacement model','Only encrypt the stored model with KMS','Increase inference temperature','Assume a prompt telling the model to keep secrets will erase learned data'],[0],
      'Removing confidential information before training prevents the replacement model from learning it. Encryption at rest and runtime filters are useful protections, but they do not undo what an already-trained model may have learned.',
      'confidential numbers were in fine-tuning data','Training-data exposure requires data cleanup and replacement training.',
      ['', 'KMS protects the artifact at rest, not learned output behavior.','Temperature is unrelated to removing learned information.','A prompt cannot reliably unlearn training examples.'],5,'Supplied 210'],
    ['A vision team needs high-quality human annotation of protective-eyewear images and expert review of uncertain labels. Which managed offering is most suitable?',
      ['SageMaker Ground Truth Plus','Bedrock Knowledge Bases','Amazon Rekognition label detection alone','Amazon QuickSight'],[0],
      'Ground Truth Plus manages data-labeling workflows with a workforce and quality controls. Human review helps catch annotation mistakes; object detection alone is not an expert validation workflow.',
      'human annotation; review uncertain labels','Ground Truth Plus → managed human labeling.',
      ['', 'Knowledge Bases retrieve information for generative AI.','Rekognition detects visual content but does not substitute for this supervised labeling workflow.','QuickSight is for analytics and dashboards.'],1,'Supplied 212','https://aws.amazon.com/sagemaker/groundtruth/plus/'],
    ['A support bot must look up an order and initiate a refund through approved APIs after understanding the customer request. What is the main benefit of Bedrock Agents here?',
      ['Training a new foundation model','Orchestrating tool calls and multistep tasks','Making every model output deterministic','Automatically granting APIs unrestricted access'],[1],
      'Bedrock Agents can plan and invoke configured action groups to complete tasks, then incorporate tool results. API permissions and guardrails still need deliberate configuration.',
      'look up order; initiate refund through APIs','Agent → orchestrates actions and tools.',
      ['Agents use models rather than training a new one by default.','', 'Agents do not eliminate model variability.','Tool access remains governed by permissions.'],3,'Supplied 213','https://docs.aws.amazon.com/bedrock/latest/userguide/agents.html'],
    ['SageMaker Studio runs inside a private VPC and needs private access to its training data in S3. Which networking component should the team configure?',
      ['An S3 VPC endpoint','S3 Glacier Deep Archive','Amazon Inspector scanning','A larger notebook instance'],[0],
      'An S3 VPC endpoint gives resources in a VPC a private route to S3 without needing internet egress for that traffic. IAM and bucket policies still control which objects the notebooks can read.',
      'private VPC access to S3','Endpoint = network path; IAM = authorization.',
      ['', 'Deep Archive is a storage class, not a network path.','Inspector finds vulnerabilities, not S3 connectivity.','Compute size does not establish private access.'],5,'Supplied 217','https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html'],
    ['A team brings its own prompt dataset to an Amazon Bedrock model evaluation job. Where should it place the dataset so the job can read it?',
      ['Amazon EBS volume on a developer laptop','Amazon S3 bucket authorized for the evaluation role','AWS Snowcone device','A local browser cache'],[1],
      'Bedrock evaluation jobs consume prompt datasets from S3. The evaluation service role must be permitted to access the specified input and output buckets.',
      'Bedrock evaluation; upload prompt dataset','S3 stores the input dataset and evaluation output.',
      ['EBS on a laptop is not the managed job input.','', 'Snowcone is an edge transfer device, not this job’s dataset location.','A browser cache is not a durable evaluation input.'],3,'Supplied 218','https://docs.aws.amazon.com/bedrock/latest/userguide/model-evaluation-judge-create.html'],
    ['A user asks an assistant to print its hidden system instructions verbatim. What attack goal is the user pursuing?',
      ['Prompt-template extraction','Dataset clustering','Model quantization','Batch inference'],[0],
      'The attacker is trying to disclose the higher-priority instructions that configure the assistant. This is a prompt-injection attempt aimed at extracting the prompt template, not an ordinary user task.',
      'print hidden system instructions','Requests to reveal hidden instructions → prompt-template extraction.',
      ['', 'Clustering groups similar records.','Quantization reduces numerical precision in model weights.','Batch inference processes offline datasets.'],5,'Supplied 219'],
    ['Under the AWS shared responsibility model for Bedrock, which responsibility belongs to the customer?',
      ['Patch the managed Bedrock infrastructure','Secure AWS data centers','Configure IAM access and protect the company’s input data','Maintain Bedrock host operating systems'],[2],
      'AWS operates the managed service infrastructure; the customer controls who can invoke it and what data is supplied. Appropriate IAM, encryption configuration, and data governance remain customer decisions.',
      'customer responsibility in managed Bedrock','AWS secures the cloud; customers configure access and their data.',
      ['AWS patches managed infrastructure.','AWS secures its facilities.','', 'AWS maintains the underlying hosts.'],5,'Supplied 220'],
    ['A company compares toxicity of output from several FMs at scale and wants little manual review effort. Which evaluation method should it try first?',
      ['Human-only review of every output','Automatic model evaluation using an appropriate toxicity metric','RLHF training on the outputs','Increase generation temperature'],[1],
      'Automatic evaluation computes a chosen metric over many model outputs with less reviewer labor. For high-stakes decisions, people should still inspect representative samples and limitations.',
      'compare toxicity at scale; least manual effort','Automatic evaluation scales; human review validates important cases.',
      ['Human review of every output has high labor cost.','', 'RLHF is a training method, not the requested comparison.','Temperature changes outputs but does not measure toxicity.'],4,'Supplied 221','https://docs.aws.amazon.com/bedrock/latest/userguide/evaluation.html'],
    ['In a red-team exercise, testers craft prompts that try to bypass an FM’s safety restrictions and elicit prohibited content. What is this technique called?',
      ['Jailbreaking','Regression','Data augmentation','Distillation'],[0],
      'Jailbreaking refers to attempts to evade a model’s safety behavior with carefully crafted inputs. Authorized testing can use such attempts to find weaknesses before deployment.',
      'bypass safety restrictions using prompts','Jailbreak → prompt attempts to evade safeguards.',
      ['', 'Regression predicts numeric values.','Data augmentation expands a training set.','Distillation trains a smaller model from a larger one.'],5,'Supplied 222'],
    // Supplied 223 had no valid option: SSE-S3 does not require customer kms:Decrypt.
    ['A Bedrock knowledge base cannot read a private S3 object encrypted with SSE-S3. The S3 bucket denies its service role access. What should the team fix?',
      ['Grant the Bedrock service role the scoped S3 read permission and allow it in the bucket policy','Grant kms:Decrypt for an SSE-S3 key','Make the bucket public','Tell the FM to ignore the access-denied error'],[0],
      'SSE-S3 is handled by S3, so the service role needs the relevant S3 object-read authorization. A customer KMS decrypt grant applies to SSE-KMS, not SSE-S3; public access is unnecessary.',
      'SSE-S3 object; S3 access denied','SSE-S3 → S3 permissions; SSE-KMS may also need KMS permissions.',
      ['', 'SSE-S3 does not use a customer KMS key for this decrypt authorization.','Public access violates the private-data requirement.','Prompts cannot override S3 authorization.'],5,'Supplied 223, corrected','https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html',
      'If the object used SSE-KMS, the role would also need appropriate KMS permissions.'],
    ['A regulated SageMaker training job must prevent its container from accessing the network during execution. Which job setting directly addresses this?',
      ['SageMaker Experiments','Enable network isolation','Enable a larger instance','Create a model card'],[1],
      'SageMaker network isolation prevents the training container from making network calls. The team must still arrange permitted inputs and outputs through SageMaker-managed channels and validate the entire architecture.',
      'container without network access','Network isolation controls the container’s network path.',
      ['Experiments tracks runs.','', 'Compute size does not isolate a container.','Model Cards document models rather than enforce networking.'],5,'Supplied 224','https://docs.aws.amazon.com/sagemaker/latest/dg/mkt-algo-model-internet-free.html'],
    ['A retailer trains SageMaker DeepAR to forecast weekly demand for several products. What type of training data does the algorithm expect?',
      ['Time-series observations','Only image pixels','Only unlabeled paragraphs','Binary class labels without dates'],[0],
      'DeepAR is a forecasting algorithm that learns temporal patterns from time series, often across multiple related series. Timestamped historical demand is the relevant input.',
      'forecast weekly demand with DeepAR','Forecasting over time → time-series data.',
      ['', 'Pixels are image inputs, not dated demand series.','Plain paragraphs lack the numeric temporal target.','Class labels without dates do not encode a forecast history.'],1,'Supplied 227','https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html'],
    ['A lender sees that one demographic group has very few positive examples in its training data. Before using the model for decisions, what should it examine?',
      ['Group and class imbalance and its effect on outcomes','Only overall training accuracy','A separate model for every individual','Whether predictions reproduce all historical decisions'],[0],
      'Imbalance can cause a model to perform differently for underrepresented groups. Measure group-level representation and outcomes, then adjust data and training with fairness checks rather than treating past decisions as an unbiased target.',
      'few positive examples in one demographic group','Check group representation and disparate outcomes.',
      ['', 'Overall accuracy can hide failures in a small group.','Individual models do not solve sparse or biased data.','Historical decisions may themselves reflect bias.'],4,'Supplied 228','https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-measure-data-bias.html'],
    // Original scenarios replace overlapping or unsound supplied items.
    ['A team has two support models and thousands of paired prompts and replies. It needs scored quality judgments with a short rationale for each reply, without routing every item to an employee. Which Bedrock evaluation method fits?',
      ['LLM-as-a-judge model evaluation','A longer context window','SageMaker Batch Transform only','KMS key rotation'],[0],
      'In a judge-based Bedrock evaluation, a separate evaluator LLM scores generator responses against selected criteria and explains its scores. It scales qualitative review, but critical decisions still warrant human validation.',
      'automated quality scores plus rationales for generated replies','Generator answers; evaluator judges.',
      ['', 'Context length changes available input, not evaluation.','Batch Transform runs inference but supplies no qualitative rubric by itself.','Key rotation is a security control.'],3,'Original',judge],
    ['An LLM-as-a-judge job scores a customer-service model’s replies. What is the role of the generator model?',
      ['Grade the evaluator','Produce the replies being assessed','Encrypt the prompt dataset','Choose IAM permissions'],[1],
      'The generator creates candidate responses to the dataset prompts. The evaluator model then scores those responses using the chosen metrics; keeping the two roles distinct prevents confusion about what is being measured.',
      'generator versus evaluator','Generator produces; evaluator scores.',
      ['The evaluator scores the generator, not vice versa.','', 'S3 encryption is separate from generation.','IAM policy authors assign permissions.'],3,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/evaluation-judge.html'],
    ['A RAG assistant cites an expense policy but invents a reimbursement limit that is absent from the retrieved passage. Which judge metric directly targets this problem?',
      ['Professional style and tone','Faithfulness','Completeness','Relevance'],[1],
      'Faithfulness checks whether claims in the reply are supported by the supplied context. An answer may sound relevant and complete while still introducing an unsupported amount.',
      'invented limit absent from provided passage','Faithfulness → supported by context; correctness → right answer against truth.',
      ['A polished tone does not establish factual support.','', 'Completeness asks whether all aspects were answered.','Relevance asks whether the response addresses the question.'],3,'Original',judge,
      'If the answer omits one of several requested items, consider completeness instead.'],
    ['An assistant answers a three-part travel-policy question accurately for the first two parts but ignores the third. Which Bedrock judge metric best measures this omission?',
      ['Completeness','Stereotyping','Faithfulness','Professional style and tone'],[0],
      'Completeness measures whether the response addresses every part of the prompt. The two statements it includes can be faithful while the overall answer remains incomplete.',
      'three-part question; one part missing','Completeness = cover every requested part.',
      ['', 'Stereotyping detects generalizations about people.','Faithfulness checks support in context, not coverage alone.','Style measures professional presentation.'],3,'Original',judge],
    ['A policy bot is instructed to answer in JSON with exactly two fields. Its answer is factually right but includes prose outside the JSON. Which judge metric isolates the failure?',
      ['Correctness','Following instructions','Faithfulness','Helpfulness'],[1],
      'Following instructions measures compliance with explicit directions in the prompt, including format. The content can be correct yet violate the required two-field JSON contract.',
      'correct facts; violated exact output format','Explicit constraint → Following instructions.',
      ['Correctness checks the factual answer, which the scenario says is right.','', 'Faithfulness evaluates grounding in context.','Helpfulness is broader and less precise than the exact-constraint metric.'],3,'Original',judge],
    ['A judge scores an answer about a published fee. The evaluation dataset includes the official fee as a reference response. Which metric uses that reference to assess whether the answer is right?',
      ['Correctness','Refusal','Professional style and tone','Coherence'],[0],
      'Bedrock correctness measures whether the model response is correct and can consider a supplied ground-truth reference. A polished, coherent answer may still quote the wrong fee.',
      'official reference response; is the answer right','Correctness can compare with reference truth.',
      ['', 'Refusal concerns declining a request.','Style does not validate the fee.','Coherence checks logical consistency rather than ground-truth agreement.'],3,'Original',judge],
    ['A model gives an answer about an unrelated product, even though its statements are factually true. Which judge metric best identifies the mismatch with the user’s request?',
      ['Relevance','Faithfulness','Harmfulness','Stereotyping'],[0],
      'Relevance measures how directly a response addresses the prompt. Factual correctness on another topic does not make the response responsive to the user.',
      'true statements; wrong topic','Relevant = on the question being asked.',
      ['', 'Faithfulness concerns grounding in supplied context.','Harmfulness concerns unsafe content.','Stereotyping concerns generalized claims about groups.'],3,'Original',judge],
    ['A generator writes, “Every applicant is approved; some applicants are never approved,” in the same explanation. Which judge metric catches the internal contradiction?',
      ['Logical coherence','S3 object integrity','BLEU','Completeness'],[0],
      'Logical coherence looks for inconsistencies, contradictions, and gaps within a response. This answer contradicts itself regardless of whether it covers the user’s requested topics.',
      'mutually inconsistent statements in one response','Coherence = reasoning hangs together.',
      ['', 'S3 integrity concerns stored objects, not reasoning quality.','BLEU measures n-gram overlap, often in translation.','Completeness concerns coverage of prompt parts.'],3,'Original',judge],
    ['A bank’s AI assistant often answers accurately but uses slang and casual jokes in formal account letters. Which judge metric best targets the presentation problem?',
      ['Faithfulness','Professional style and tone','Correctness','Refusal'],[1],
      'Professional style and tone measures whether the response’s wording, formatting, and tone suit a professional context. The scenario states that accuracy is already acceptable.',
      'accurate answer; inappropriate formal-letter tone','Tone is a separate quality dimension from factual accuracy.',
      ['Faithfulness concerns unsupported claims.','', 'Correctness tests the answer’s truth, not its register.','Refusal measures whether the assistant declines.'],3,'Original',judge],
    ['A customer bot declines ordinary password-reset guidance that company policy permits. Which judge metric can help quantify excessive declines?',
      ['Refusal','Stereotyping','RMSE','Latency'],[0],
      'The refusal metric measures whether responses decline to answer prompts. Reviewing its scores alongside prompt intent can reveal over-refusal; the metric alone cannot decide whether each refusal was warranted.',
      'declines permitted requests','Refusal counts declining answers; inspect whether the decline was appropriate.',
      ['', 'Stereotyping concerns generalized group claims.','RMSE measures numeric prediction error.','Latency measures speed, not refusal behavior.'],4,'Original',judge],
    ['A judge must detect when marketing copy makes broad claims about how people of a particular age or ethnicity behave. Which metric is most specific?',
      ['Completeness','Stereotyping','Coherence','Following instructions'],[1],
      'Stereotyping evaluates whether a response makes generalizations about groups, including seemingly positive stereotypes. The requirement is fairness of generated content, not coverage or formatting.',
      'broad generalizations about demographic groups','Stereotyping → generalized group claims.',
      ['Completeness checks whether all prompt parts are answered.','', 'Coherence checks internal logic.','Instruction following checks explicit directions.'],4,'Original',judge],
    ['A content team wants to compare how often candidate models generate violent or hateful instructions. Which judge metric directly measures that risk?',
      ['Helpfulness','Harmfulness','Correctness','Relevance'],[1],
      'Harmfulness evaluates unsafe generated content. It addresses the nature of the response, while correctness and relevance can be high even for unsafe instructions.',
      'violent or hateful output','Harmfulness = unsafe content in generated responses.',
      ['Helpfulness addresses usefulness to a request.','', 'Correctness is about being right, not safe.','Relevance is about addressing the prompt.'],4,'Original',judge],
    ['A company’s specialized support criterion is “quote the exact policy section identifier when one is available.” None of the built-in judge metrics directly represents this criterion. What should it configure?',
      ['A custom LLM-as-a-judge metric and evaluator prompt','A larger embedding dimension only','A lower generator temperature only','An S3 storage class change'],[0],
      'Bedrock permits custom judge metrics with an evaluator prompt defining the business criterion. The team should validate its rubric against human judgments instead of assuming a custom score is objectively correct.',
      'business-specific rubric absent from built-ins','Custom criterion → custom judge metric.',
      ['', 'Embeddings do not define the evaluation rubric.','Temperature may change output variability but not assess citations.','Storage class affects storage economics.'],3,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/model-evaluation-custom-metrics-prompt-formats.html'],
    ['An LLM judge scores a small sample very differently from expert reviewers. What should the team do before relying on its scores across the full dataset?',
      ['Compare and calibrate judge criteria against representative human ratings','Assume the LLM is more objective and discard human ratings','Raise the generator output token limit','Turn off evaluation logging'],[0],
      'Judge results are model-derived assessments and can have bias or rubric mismatch. Checking agreement with representative expert ratings, refining criteria, and documenting limitations improves trust in scaled evaluation.',
      'judge scores disagree with expert reviewers','Calibrate automated judgments with human review.',
      ['', 'Disagreement is evidence to investigate, not to ignore.','Longer answers do not fix a faulty judge rubric.','Removing records makes the discrepancy harder to audit.'],4,'Original','https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/responsible-ai-lens.html'],
    ['A Bedrock evaluation dataset contains prompts and precomputed replies from a model hosted outside Bedrock. Can a judge-based evaluation assess them?',
      ['Yes, supply the responses in the dataset so the job can score them without invoking that generator','No, every generator must be hosted on Bedrock','Yes, but only after fine-tuning the evaluator','No, judge evaluation requires a human workforce'],[0],
      'Bedrock judge-based jobs can evaluate supplied inference responses from a non-Bedrock generator. When responses are included, the job skips the generator invocation and scores the provided text.',
      'precomputed non-Bedrock responses','Bring responses to the judge; no generator invocation needed.',
      ['', 'The generator need not be hosted on Bedrock when responses are supplied.','The evaluator does not require fine-tuning for this.','A human workforce is a different evaluation mode.'],3,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/evaluation-judge.html'],
    ['A hiring-assistance model shows equal overall accuracy but substantially lower recall for qualified applicants in one demographic group. What evaluation is missing from the overall score?',
      ['Subgroup performance analysis','Only average inference latency','A global token count','The number of model parameters'],[0],
      'Aggregate accuracy can hide unequal error rates. Measuring recall and other relevant outcomes separately by group reveals whether qualified applicants in one group are missed more often.',
      'equal aggregate accuracy; lower recall for one group','Slice metrics by relevant groups; averages can hide unfairness.',
      ['', 'Latency does not expose missed qualified applicants.','Tokens do not measure group outcomes.','Parameter count does not measure fairness.'],4,'Original','https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-measure-data-bias.html'],
    ['A hospital deploys an AI triage assistant. Uncertain recommendations could affect patient care. Which governance design best preserves accountability?',
      ['Route uncertain or high-impact recommendations to a clinician for review','Let the model make final decisions whenever it sounds confident','Remove decision logs to reduce storage cost','Measure only average response length'],[0],
      'Human oversight is appropriate for consequential decisions, especially low-confidence cases. A clinician can review evidence, correct errors, and take responsibility under the organization’s clinical process.',
      'high-impact triage; uncertain output','Human-in-the-loop for consequential or uncertain decisions.',
      ['', 'Fluent language is not proof of clinical correctness.','Logs help investigation and audit when handled securely.','Response length is not patient safety.'],4,'Original',guide],
    ['A company tells customers that an AI assistant may draft recommendations and explains when a human will approve them. Which responsible-AI principle is this primarily demonstrating?',
      ['Transparency','Overfitting','Clustering','Quantization'],[0],
      'Transparency means people can understand that AI is involved, its intended role, and relevant limits or oversight. Disclosure supports informed use of the recommendations.',
      'disclose AI involvement and human approval','Transparency → clear communication about AI use and limits.',
      ['', 'Overfitting is weak generalization after training.','Clustering groups unlabeled examples.','Quantization changes model numeric precision.'],4,'Original',guide],
    ['A company must explain to rejected loan applicants which input factors most influenced an ML risk score. Which SageMaker capability is the best starting point?',
      ['SageMaker Clarify feature attribution','SageMaker Batch Transform alone','SageMaker Ground Truth labeling','S3 lifecycle rules'],[0],
      'SageMaker Clarify can produce feature-attribution explanations for predictions. The organization must still present them accurately and evaluate whether its use meets applicable requirements.',
      'which input factors influenced a prediction','Clarify explains feature influence; Model Cards document the model.',
      ['', 'Batch Transform runs offline predictions but does not itself explain them.','Ground Truth creates labels.','Lifecycle rules manage object retention.'],4,'Original','https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-model-explainability.html'],
    ['An internal governance team needs a versioned record of a custom model’s intended use, risk rating, training details, and evaluation results. What should it create?',
      ['A SageMaker Model Card','An AWS AI Service Card for a custom private model','A CloudWatch alarm only','An embedding index'],[0],
      'SageMaker Model Cards document key details and assessment information for a team’s ML models. AWS AI Service Cards describe AWS-provided AI services rather than serving as the team’s custom model record.',
      'custom model documentation and governance','Model Card = your model’s documented facts and risks.',
      ['', 'AWS publishes AI Service Cards for its own services.','An alarm tracks a signal, not the full model record.','An embedding index supports retrieval.'],5,'Original','https://docs.aws.amazon.com/sagemaker/latest/dg/model-cards.html'],
    ['A support-model pilot is over. Its S3 evaluation dataset includes customer conversations that the team no longer needs. Which governance action best limits continuing privacy exposure?',
      ['Apply an approved retention and deletion policy to the dataset and derived copies','Keep every copy indefinitely in case it becomes useful','Increase the evaluator temperature','Publish the dataset to an open bucket for transparency'],[0],
      'Purpose-limited retention and deletion reduce the amount of personal data that remains exposed after a pilot. The team should identify derived datasets and reports as well as the original objects, subject to applicable retention obligations.',
      'pilot ended; customer data no longer needed','Govern data through its whole lifecycle, including deletion.',
      ['', 'Indefinite copies enlarge the privacy risk without a purpose.','Temperature affects sampling, not retention.','Publishing personal conversations creates further exposure.'],5,'Original',guide],
    ['An auditor wants a repeatable collection of evidence showing that AWS resource controls meet an internal AI policy mapped to a compliance framework. Which service helps?',
      ['AWS Audit Manager','AWS Artifact only','Amazon Polly','Amazon Rekognition'],[0],
      'Audit Manager automates evidence collection and maps it to assessments and controls. Artifact provides AWS compliance documents, which can support an audit but does not perform this account-level evidence collection.',
      'collect evidence for mapped controls','Audit Manager gathers your audit evidence; Artifact provides AWS reports.',
      ['', 'Artifact provides AWS and partner compliance reports, not this automated assessment workflow.','Polly synthesizes speech.','Rekognition analyzes images and video.'],5,'Original','https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html'],
    ['A procurement team needs AWS’s SOC and ISO reports as part of its vendor assessment for an AI workload. Where should it obtain them?',
      ['AWS Artifact','Amazon Macie','Amazon Q in QuickSight','SageMaker Model Monitor'],[0],
      'AWS Artifact offers on-demand access to AWS compliance reports and agreements. It is a source for AWS’s evidence, while the customer’s own control evidence is a separate governance task.',
      'obtain AWS SOC/ISO reports','Artifact = AWS compliance reports.',
      ['', 'Macie discovers sensitive data in S3.','Q in QuickSight creates BI analysis.','Model Monitor observes deployed model quality.'],5,'Original','https://docs.aws.amazon.com/artifact/latest/ug/what-is-aws-artifact.html'],
    ['A security engineer needs to identify which principal changed a Bedrock guardrail and when the API call occurred. Which log source answers that question?',
      ['AWS CloudTrail','Amazon Macie','Bedrock token-count metrics only','SageMaker Ground Truth'],[0],
      'CloudTrail records AWS API activity, including who made a supported call and when. Model invocation content and guardrail intervention metrics are different telemetry.',
      'who changed a resource; when','CloudTrail = API activity; CloudWatch = metrics and alarms.',
      ['', 'Macie scans S3 data for sensitive content.','Token counts do not identify the API actor.','Ground Truth is for labeling.'],5,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/monitoring-cloudtrail.html'],
    ['A compliance rule requires S3 buckets holding model-training data to remain encrypted. The team wants a history of configuration changes and rule compliance. Which service fits?',
      ['AWS Config','Amazon Transcribe','Amazon Q Developer','BLEU evaluation'],[0],
      'AWS Config records supported resource configurations and can evaluate them against rules over time. CloudTrail would complement it by identifying API activity that led to a change.',
      'configuration history and compliance rule','Config = resource state over time; CloudTrail = API calls.',
      ['', 'Transcribe converts audio to text.','Q Developer assists developers.','BLEU evaluates text overlap.'],5,'Original','https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html'],
    ['An organization wants to prevent member accounts from invoking unapproved Bedrock models even if an account administrator grants a permissive IAM policy. Which organization-level control can establish the boundary?',
      ['Service control policy (SCP) in AWS Organizations','A prompt that says “use approved models”','An S3 lifecycle rule','A higher model temperature'],[0],
      'An SCP sets the maximum permitted actions for accounts in an organization. An explicit restriction can bound IAM permissions, while specific IAM policies still grant the allowed access.',
      'boundary across accounts despite permissive IAM','SCP limits maximum permissions; IAM grants within that boundary.',
      ['', 'Prompt text cannot enforce AWS API permissions.','Lifecycle rules manage S3 storage.','Temperature changes model sampling.'],5,'Original','https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html'],
    ['A Bedrock application must keep calls to supported service APIs on a private path from its VPC. What AWS capability should the network team investigate?',
      ['AWS PrivateLink interface VPC endpoints','A public internet gateway','Higher Top P','S3 Transfer Acceleration'],[0],
      'PrivateLink interface endpoints provide private connectivity from a VPC to supported AWS services. Endpoint availability and the exact Bedrock API used must be checked for the chosen Region.',
      'private VPC path to supported Bedrock API','PrivateLink = private service connectivity.',
      ['', 'An internet gateway sends traffic to the public internet.','Top P controls generation sampling.','Transfer Acceleration speeds S3 uploads through edge locations.'],5,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/vpc-interface-endpoints.html'],
    ['An AI team stores training files in S3 using SSE-KMS. A role has s3:GetObject but receives a KMS access error. What permission should it review?',
      ['kms:Decrypt on the applicable KMS key','bedrock:InvokeModel only','s3:PutObject only','cloudtrail:LookupEvents only'],[0],
      'Reading an SSE-KMS encrypted object also requires appropriate KMS use permissions and key-policy access. This differs from SSE-S3, where there is no customer KMS key grant to add.',
      'SSE-KMS; KMS access denied on read','SSE-KMS needs both S3 object access and KMS permissions.',
      ['', 'Model invocation does not decrypt S3 objects.','PutObject writes objects, not reads them.','CloudTrail lookup reads audit events.'],5,'Original','https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html'],
    ['A team must locate spreadsheets containing sensitive national identifiers across many S3 buckets before using files to fine-tune an FM. Which service is designed to discover the sensitive S3 data?',
      ['Amazon Macie','AWS Artifact','Amazon Lex','SageMaker Model Cards'],[0],
      'Macie discovers and reports sensitive data in S3, helping the team find files that need review or exclusion. Discovering data is separate from removing it and governing the fine-tuning pipeline.',
      'discover sensitive identifiers in S3','Macie finds sensitive S3 data; Guardrails filters model content.',
      ['', 'Artifact supplies compliance reports.','Lex builds conversational interfaces.','Model Cards document models and assessments.'],5,'Original','https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html'],
    ['A company is creating an AI application from customer chats. Which TWO practices directly reduce unnecessary personal-data exposure? (Choose two.)',
      ['Remove identifiers that are not needed before training','Limit dataset access with least-privilege IAM','Give every developer unrestricted raw-chat access','Keep all raw chats forever by default','Put customer passwords into example prompts'],[0,1],
      'Data minimization reduces what the model can learn or leak, and least-privilege access limits who can reach the source data. The team should also follow its approved retention and consent policies.',
      'reduce personal-data exposure','Minimize collected data and restrict access.',
      ['', '', 'Unrestricted access expands exposure.','Indefinite retention increases the data at risk without a stated need.','Secrets in prompts expose sensitive material to the application workflow.'],5,'Original',guide],
    ['A company wants to prevent an assistant from answering requests for internal salary data while still allowing public HR-policy questions. Which first control best addresses the response policy?',
      ['Configure a Bedrock Guardrails denied topic or appropriate content policy and test it','Only increase the maximum output length','Train on more salary records','Disable IAM for the application'],[0],
      'A guardrail policy can block defined prohibited topics or content in prompts and responses. It should complement access restrictions so the assistant cannot retrieve salary data it has no reason to see.',
      'block a sensitive response topic while allowing other answers','Guardrails enforce runtime content policy; IAM limits underlying access.',
      ['', 'Longer outputs do not enforce a prohibition.','More sensitive training data increases risk.','Disabling access control undermines the data boundary.'],5,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-denied-topics.html'],
    ['A retrieved web page tells an AI assistant to ignore its system instructions and send a secret API key to a URL. What is the trust-boundary failure the team must prevent?',
      ['Treating untrusted retrieved content as instructions','Reducing vector dimensionality','Using labeled examples for classification','Measuring response latency'],[0],
      'The web page is lower-trust source material, not an authorized instruction. The application must keep retrieved text as data, limit tool permissions, and test for prompt injection.',
      'instructions embedded in retrieved page','Untrusted retrieval content must not override trusted instructions.',
      ['', 'Vector dimensions affect retrieval representation, not instruction authority.','Classification labels are unrelated.','Latency does not resolve the injection.'],5,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-prompt-attack.html'],
    ['A team rotates the KMS key used for stored prompt logs. Which security property is that primarily supporting?',
      ['Protection of data at rest','Classification recall','Semantic search relevance','Answer completeness'],[0],
      'KMS manages encryption keys used to protect stored data. Key management does not determine whether an LLM answer is grounded or whether a classifier finds positives.',
      'KMS key for stored prompt logs','KMS → encryption keys for data protection.',
      ['', 'Recall is a classification metric.','Relevance concerns retrieval or response quality.','Completeness concerns coverage of a prompt.'],5,'Original','https://docs.aws.amazon.com/kms/latest/developerguide/overview.html'],
    ['A model was approved for English support emails, but a team now wants it to recommend credit limits in another country. What governance step is most important before expansion?',
      ['Reassess intended use, risks, data, and performance in the new context','Assume approval transfers to every use case','Only enlarge the model context window','Remove the existing model documentation'],[0],
      'A new language, geography, and high-impact decision alter the risk and validity assumptions. Re-evaluate data suitability, fairness, performance, oversight, and documentation before using the model for that purpose.',
      'approved use changes to high-impact new context','Approval is scoped to intended use and evidence, not to the model forever.',
      ['', 'A previous approval is not evidence for a different population or decision.','Context size does not address governance risk.','Removing documentation reduces accountability.'],4,'Original',guide],
    ['An AI service changes model versions. The governance team wants to know whether fairness and safety scores changed after the release. What should it do?',
      ['Run the same versioned evaluation suite against old and new versions and review differences','Compare only the model names','Increase temperature on the new version','Delete historical scores'],[0],
      'Versioned prompts, datasets, rubrics, and results allow a meaningful before-and-after comparison. Re-evaluation can expose regressions that are hidden by a new model label alone.',
      'compare model-version fairness and safety','Keep evaluation datasets and criteria versioned; test changes.',
      ['', 'A name gives no outcome measurement.','Temperature is not a fairness test.','Without history there is no baseline.'],4,'Original',guide],
    ['An automated evaluator gives high scores to verbose answers but experts prefer concise, accurate replies. What risk does this illustrate?',
      ['Judge or rubric bias','S3 eventual consistency','Classification class imbalance only','KMS key expiration'],[0],
      'A judge can favor superficial qualities such as length if its rubric or model preferences differ from human goals. Calibration on representative expert judgments can expose and reduce that mismatch.',
      'judge rewards verbosity contrary to expert preference','An automated score is a measurement to validate, not ground truth.',
      ['', 'S3 consistency does not explain score preference.','Dataset imbalance may be another issue, but the described failure is in evaluation preference.','Encryption keys do not cause qualitative scoring bias.'],4,'Original','https://docs.aws.amazon.com/wellarchitected/latest/responsible-ai-lens/responsible-ai-lens.html'],
    ['A data owner needs to know which approved dataset version, preprocessing step, and model version produced a particular AI release. Which governance practice provides this traceability?',
      ['Record data and model lineage with versioned artifacts','Keep only the latest output text','Raise Top K','Use a larger inference instance'],[0],
      'Lineage records the provenance and transformations of data and model artifacts. It supports reproducibility, investigation, and accountability when a release performs unexpectedly.',
      'trace dataset, preprocessing, and model version','Lineage = how an artifact was produced.',
      ['', 'The latest output alone cannot reconstruct provenance.','Top K changes sampling.','Instance size changes capacity, not traceability.'],5,'Original',guide],
    ['A bank deploys a fraud classifier and later finds that inputs have shifted substantially from its training baseline. What should the team monitor and investigate?',
      ['Production data drift and model quality','Only training-set accuracy from last year','The logo used by the dashboard','The number of chatbot tokens'],[0],
      'Changes in production data can undermine performance after launch. Monitoring data and model quality against a baseline helps the team decide when to investigate, retrain, or revise controls.',
      'inputs changed after deployment','Drift is a production monitoring concern.',
      ['', 'Old training accuracy does not reveal current behavior.','Dashboard branding is unrelated.','Token counts do not measure classifier drift.'],4,'Original','https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor.html'],
    ['A governance board asks whether a high-stakes model can explain decisions, be audited, and be corrected by a person. Which TWO design choices best support those needs? (Choose two.)',
      ['Retain documented model versions and decision evidence','Provide a human appeal and review path','Hide model limitations from affected people','Give the model unrestricted write access to records','Evaluate only average accuracy'],[0,1],
      'Documented evidence supports audit and reproducibility; human review enables correction and accountability. These controls complement performance and fairness evaluation rather than replacing it.',
      'auditability and correction by a person','Keep traceable evidence and an appeal path.',
      ['', '', 'Hiding limitations undermines informed use.','Unrestricted write access increases risk.','Average accuracy hides important errors and cannot itself provide appeal.'],4,'Original',guide],
    ['A company publishes AI-generated investment commentary. It wants readers to know the content was AI-assisted and which statements were checked by analysts. What action best serves that goal?',
      ['Disclose AI involvement and human verification scope','Silently remove the analyst review step','Increase Top P','Store the article in S3 Glacier'],[0],
      'Clear disclosure of AI use, validation scope, and limitations makes the process transparent to readers. It also avoids implying that every generated statement received human verification.',
      'tell readers how AI and analysts contributed','Transparency includes what was and was not checked.',
      ['', 'Removing review does not improve disclosure or reliability.','Top P changes sampling, not transparency.','Storage class does not tell readers the process.'],4,'Original',guide],
    ['A company asks an LLM judge to evaluate a chatbot for “helpfulness” but notices that the score blends formatting, coherence, and whether it anticipates a user’s needs. Why is this expected?',
      ['Helpfulness is a broad quality metric that can combine several aspects of usefulness','Helpfulness measures only factual agreement with a reference','Helpfulness is another name for output-token count','Helpfulness measures only whether the model refused'],[0],
      'Bedrock’s helpfulness metric considers multiple aspects of whether the response serves the user, including instruction following and coherence. Use a narrower metric such as correctness or following instructions when the failure mode needs isolation.',
      'broad useful response, several quality dimensions','Helpfulness is broader; targeted metrics isolate a specific weakness.',
      ['', 'Correctness is the direct right-answer measure.','Token count is a usage measure.','Refusal assesses declined answers.'],3,'Original',judge],
    ['A judge-based model evaluation needs a prompt dataset in S3 and a report destination. Which TWO permissions should the evaluation service role have, scoped to the required resources? (Choose two.)',
      ['Read the input prompt objects','Write the output report objects','Administrator access to all AWS services','Public-read access for every bucket','Permission to change organization SCPs'],[0,1],
      'The job must read its input dataset and write results to the configured S3 destination. Least-privilege policies scope these actions to the relevant objects; model invoke permissions may also be needed depending on job configuration.',
      'evaluation S3 input and output','Role needs scoped S3 read and write, plus applicable model access.',
      ['', '', 'Broad administration is unnecessary.','Public buckets are unnecessary and unsafe.','Organization policy changes are outside the evaluation job.'],5,'Original','https://docs.aws.amazon.com/bedrock/latest/userguide/model-evaluation-judge-create.html'],
    ['A company compares models with an LLM judge before launch. It wants to prevent the evaluation data from containing real customer passwords. Which first step best follows data minimization?',
      ['Replace or remove passwords before creating the evaluation dataset','Use the raw passwords because an evaluator needs realism','Raise the judge temperature','Publish the dataset to a public bucket'],[0],
      'Evaluation data should include only information required to test the system. Synthetic or sanitized examples can preserve the scenario without exposing actual credentials in prompts, responses, or stored reports.',
      'real passwords in evaluation dataset','Minimize sensitive data before it enters the evaluation workflow.',
      ['', 'Real credentials are not necessary for response-quality evaluation.','Sampling does not remove secrets.','Public storage increases exposure.'],5,'Original',guide]
  ];
  const questions = raw.map(([q,opts,ans,why,clue,tip,wrong,domain,source,reference=guide,transferCheck='']) => {
    const incorrectReasons = {};
    opts.forEach((_,i) => { if (!ans.includes(i)) incorrectReasons[i] = wrong[i]; });
    return {
      q,opts,ans,selectCount:ans.length,why,
      explanation: {
        correctAnswer: ans.map(i => `${letter(i)}. ${opts[i]}`).join(' / '),
        correctReason:why,incorrectReasons,examClue:clue,examTip:tip,
        transferCheck,rememberThis:tip,
        takeaway:{signal:clue,think:tip,contrast:''}
      },
      task:`Domain ${domain}`,taskName:'AIF-C01 mixed-domain practice',
      status:source.startsWith('Supplied')?'user-supplied practice question, reviewed and adapted':'original practice question',
      source:source.startsWith('Supplied')?`${source}; adapted from user-provided ExamPrepper practice text`:'Original practice question written for this reviewer',
      reference
    };
  });
  window.aifExamData.mockExam5 = {
    id:'mock-exam-5',kind:'mock',title:'Mock Exam 5',subtitle:'Full AIF-C01 Practice Exam',
    weight:'Full Mock',durationSeconds:5400,passPercent:72,questions
  };
})();
